name: tugas_4
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'  # Memperbarui rentang SDK ke versi yang direkomendasikan

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avatar.png  # Pastikan file avatar.png tersedia di lokasi assets

